- name: Deploy Docker Application
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Deploy application
      docker_container:
        name: my_app
        image: my_docker_image:latest
        state: started
        ports:
          - "80:80"
